//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.SendNotificationForMutsDemandRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.AuthenticateRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ProductSearchRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetLocationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.SubmitLocationActionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetLocationsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetLightUrunModelRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.CheckHesCodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetLabelInfoRequest))]
    public partial class RequestBase : object
    {
        
        private string LanguageIsoCodeField;
        
        private string StoreCodeField;
        
        private string TerminalIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageIsoCode
        {
            get
            {
                return this.LanguageIsoCodeField;
            }
            set
            {
                this.LanguageIsoCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreCode
        {
            get
            {
                return this.StoreCodeField;
            }
            set
            {
                this.StoreCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalId
        {
            get
            {
                return this.TerminalIdField;
            }
            set
            {
                this.TerminalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendNotificationForMutsDemandRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request.PushNotificatio" +
        "n")]
    public partial class SendNotificationForMutsDemandRequest : ServiceReference1.RequestBase
    {
        
        private ServiceReference1.SendNotificationForMutsDemandEntity[] SendNotificationForMutsDemandEntityListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.SendNotificationForMutsDemandEntity[] SendNotificationForMutsDemandEntityList
        {
            get
            {
                return this.SendNotificationForMutsDemandEntityListField;
            }
            set
            {
                this.SendNotificationForMutsDemandEntityListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticateRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class AuthenticateRequest : ServiceReference1.RequestBase
    {
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSearchRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class ProductSearchRequest : ServiceReference1.RequestBase
    {
        
        private string BarkodOrOzelkodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BarkodOrOzelkod
        {
            get
            {
                return this.BarkodOrOzelkodField;
            }
            set
            {
                this.BarkodOrOzelkodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocationRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class GetLocationRequest : ServiceReference1.RequestBase
    {
        
        private string LocationBarcodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationBarcode
        {
            get
            {
                return this.LocationBarcodeField;
            }
            set
            {
                this.LocationBarcodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitLocationActionRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class SubmitLocationActionRequest : ServiceReference1.RequestBase
    {
        
        private ServiceReference1.LocationActionModel[] LocationActionListField;
        
        private string LocationBarcodeField;
        
        private int SubmitTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.LocationActionModel[] LocationActionList
        {
            get
            {
                return this.LocationActionListField;
            }
            set
            {
                this.LocationActionListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationBarcode
        {
            get
            {
                return this.LocationBarcodeField;
            }
            set
            {
                this.LocationBarcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubmitType
        {
            get
            {
                return this.SubmitTypeField;
            }
            set
            {
                this.SubmitTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocationsRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class GetLocationsRequest : ServiceReference1.RequestBase
    {
        
        private int DepoRefField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepoRef
        {
            get
            {
                return this.DepoRefField;
            }
            set
            {
                this.DepoRefField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLightUrunModelRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class GetLightUrunModelRequest : ServiceReference1.RequestBase
    {
        
        private string BarcodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode
        {
            get
            {
                return this.BarcodeField;
            }
            set
            {
                this.BarcodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckHesCodeRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class CheckHesCodeRequest : ServiceReference1.RequestBase
    {
        
        private string HesCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesCode
        {
            get
            {
                return this.HesCodeField;
            }
            set
            {
                this.HesCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLabelInfoRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class GetLabelInfoRequest : ServiceReference1.RequestBase
    {
        
        private string BarcodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode
        {
            get
            {
                return this.BarcodeField;
            }
            set
            {
                this.BarcodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendNotificationForMutsDemandEntity", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request.PushNotificatio" +
        "n")]
    public partial class SendNotificationForMutsDemandEntity : object
    {
        
        private string NotificationDetailField;
        
        private string NotificationTitleField;
        
        private string StoreCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationDetail
        {
            get
            {
                return this.NotificationDetailField;
            }
            set
            {
                this.NotificationDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationTitle
        {
            get
            {
                return this.NotificationTitleField;
            }
            set
            {
                this.NotificationTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreCode
        {
            get
            {
                return this.StoreCodeField;
            }
            set
            {
                this.StoreCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationActionModel", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class LocationActionModel : object
    {
        
        private string BarcodeField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode
        {
            get
            {
                return this.BarcodeField;
            }
            set
            {
                this.BarcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.SendNotificationForMutsDemandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.AuthenticateResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ProductSearchResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.AuthCodeToTokenResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.TransferExceptionLogResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetLocationResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.SubmitLocationActionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetLocationsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetLightUrunModelResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.CheckHesCodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.GetLabelInfoResponse))]
    public partial class ResponseBase : object
    {
        
        private bool HasErrorField;
        
        private string ResultMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError
        {
            get
            {
                return this.HasErrorField;
            }
            set
            {
                this.HasErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultMessage
        {
            get
            {
                return this.ResultMessageField;
            }
            set
            {
                this.ResultMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendNotificationForMutsDemandResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response.PushNotificati" +
        "on")]
    public partial class SendNotificationForMutsDemandResponse : ServiceReference1.ResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticateResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class AuthenticateResponse : ServiceReference1.ResponseBase
    {
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSearchResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class ProductSearchResponse : ServiceReference1.ResponseBase
    {
        
        private ServiceReference1.ProductSearchViewModel[] ProductSearchListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProductSearchViewModel[] ProductSearchList
        {
            get
            {
                return this.ProductSearchListField;
            }
            set
            {
                this.ProductSearchListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthCodeToTokenResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class AuthCodeToTokenResponse : ServiceReference1.ResponseBase
    {
        
        private ServiceReference1.AuthModel AuthModelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.AuthModel AuthModel
        {
            get
            {
                return this.AuthModelField;
            }
            set
            {
                this.AuthModelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferExceptionLogResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class TransferExceptionLogResponse : ServiceReference1.ResponseBase
    {
        
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess
        {
            get
            {
                return this.IsSuccessField;
            }
            set
            {
                this.IsSuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocationResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class GetLocationResponse : ServiceReference1.ResponseBase
    {
        
        private string LocationBarcodeField;
        
        private string LocationDefinitionField;
        
        private int TotalCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationBarcode
        {
            get
            {
                return this.LocationBarcodeField;
            }
            set
            {
                this.LocationBarcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationDefinition
        {
            get
            {
                return this.LocationDefinitionField;
            }
            set
            {
                this.LocationDefinitionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount
        {
            get
            {
                return this.TotalCountField;
            }
            set
            {
                this.TotalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitLocationActionResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class SubmitLocationActionResponse : ServiceReference1.ResponseBase
    {
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocationsResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class GetLocationsResponse : ServiceReference1.ResponseBase
    {
        
        private ServiceReference1.Location[] LocationListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Location[] LocationList
        {
            get
            {
                return this.LocationListField;
            }
            set
            {
                this.LocationListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLightUrunModelResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class GetLightUrunModelResponse : ServiceReference1.ResponseBase
    {
        
        private ServiceReference1.LightUrunModel LightUrunModelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.LightUrunModel LightUrunModel
        {
            get
            {
                return this.LightUrunModelField;
            }
            set
            {
                this.LightUrunModelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckHesCodeResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class CheckHesCodeResponse : ServiceReference1.ResponseBase
    {
        
        private string CurrentHealthStatusField;
        
        private System.DateTime ExpirationDateField;
        
        private string MaskedFirstnameField;
        
        private string MaskedIdentityNumberField;
        
        private string MaskedLastnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentHealthStatus
        {
            get
            {
                return this.CurrentHealthStatusField;
            }
            set
            {
                this.CurrentHealthStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaskedFirstname
        {
            get
            {
                return this.MaskedFirstnameField;
            }
            set
            {
                this.MaskedFirstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaskedIdentityNumber
        {
            get
            {
                return this.MaskedIdentityNumberField;
            }
            set
            {
                this.MaskedIdentityNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaskedLastname
        {
            get
            {
                return this.MaskedLastnameField;
            }
            set
            {
                this.MaskedLastnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLabelInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class GetLabelInfoResponse : ServiceReference1.ResponseBase
    {
        
        private ServiceReference1.LabelDetail LabelDetailField;
        
        private ServiceReference1.PriceDetail PriceDetailField;
        
        private ServiceReference1.ProductDetail ProductDetailField;
        
        private ServiceReference1.StockDetail StockDetailField;
        
        private ServiceReference1.TransferDetail TransferDetailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.LabelDetail LabelDetail
        {
            get
            {
                return this.LabelDetailField;
            }
            set
            {
                this.LabelDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PriceDetail PriceDetail
        {
            get
            {
                return this.PriceDetailField;
            }
            set
            {
                this.PriceDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProductDetail ProductDetail
        {
            get
            {
                return this.ProductDetailField;
            }
            set
            {
                this.ProductDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.StockDetail StockDetail
        {
            get
            {
                return this.StockDetailField;
            }
            set
            {
                this.StockDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TransferDetail TransferDetail
        {
            get
            {
                return this.TransferDetailField;
            }
            set
            {
                this.TransferDetailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LabelDetail", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class LabelDetail : object
    {
        
        private string AtamaTarihField;
        
        private string BuyukBeyazEtiketZplField;
        
        private System.Nullable<int> EtiketTipField;
        
        private bool FirsatUrunuMuField;
        
        private System.Nullable<System.DateTime> FiyatDegisimTarihField;
        
        private string IcBarkodEtiketZplField;
        
        private string IlkFiyatDegisimEtiketZplField;
        
        private string IndirimliEtiketZplField;
        
        private System.Nullable<decimal> IskontoOranField;
        
        private string KontrolBarkodField;
        
        private bool TaksitEngelliMiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtamaTarih
        {
            get
            {
                return this.AtamaTarihField;
            }
            set
            {
                this.AtamaTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyukBeyazEtiketZpl
        {
            get
            {
                return this.BuyukBeyazEtiketZplField;
            }
            set
            {
                this.BuyukBeyazEtiketZplField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EtiketTip
        {
            get
            {
                return this.EtiketTipField;
            }
            set
            {
                this.EtiketTipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FirsatUrunuMu
        {
            get
            {
                return this.FirsatUrunuMuField;
            }
            set
            {
                this.FirsatUrunuMuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FiyatDegisimTarih
        {
            get
            {
                return this.FiyatDegisimTarihField;
            }
            set
            {
                this.FiyatDegisimTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcBarkodEtiketZpl
        {
            get
            {
                return this.IcBarkodEtiketZplField;
            }
            set
            {
                this.IcBarkodEtiketZplField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IlkFiyatDegisimEtiketZpl
        {
            get
            {
                return this.IlkFiyatDegisimEtiketZplField;
            }
            set
            {
                this.IlkFiyatDegisimEtiketZplField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndirimliEtiketZpl
        {
            get
            {
                return this.IndirimliEtiketZplField;
            }
            set
            {
                this.IndirimliEtiketZplField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> IskontoOran
        {
            get
            {
                return this.IskontoOranField;
            }
            set
            {
                this.IskontoOranField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KontrolBarkod
        {
            get
            {
                return this.KontrolBarkodField;
            }
            set
            {
                this.KontrolBarkodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TaksitEngelliMi
        {
            get
            {
                return this.TaksitEngelliMiField;
            }
            set
            {
                this.TaksitEngelliMiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceDetail", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class PriceDetail : object
    {
        
        private System.Nullable<double> IlkPesinFiyatField;
        
        private System.Nullable<double> IlkTaksitliFiyatField;
        
        private System.Nullable<double> PesinFiyatField;
        
        private System.Nullable<double> TaksitliFiyatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> IlkPesinFiyat
        {
            get
            {
                return this.IlkPesinFiyatField;
            }
            set
            {
                this.IlkPesinFiyatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> IlkTaksitliFiyat
        {
            get
            {
                return this.IlkTaksitliFiyatField;
            }
            set
            {
                this.IlkTaksitliFiyatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PesinFiyat
        {
            get
            {
                return this.PesinFiyatField;
            }
            set
            {
                this.PesinFiyatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TaksitliFiyat
        {
            get
            {
                return this.TaksitliFiyatField;
            }
            set
            {
                this.TaksitliFiyatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDetail", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class ProductDetail : object
    {
        
        private string AdField;
        
        private string BarkodField;
        
        private string BedenField;
        
        private int BedenSiraField;
        
        private string LineTanimField;
        
        private string OzelKodField;
        
        private string RenkField;
        
        private string RenkHexKodField;
        
        private string RenkKodField;
        
        private int UrunIdField;
        
        private string UrunKlasmanField;
        
        private bool YerliMaliMiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barkod
        {
            get
            {
                return this.BarkodField;
            }
            set
            {
                this.BarkodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beden
        {
            get
            {
                return this.BedenField;
            }
            set
            {
                this.BedenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BedenSira
        {
            get
            {
                return this.BedenSiraField;
            }
            set
            {
                this.BedenSiraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineTanim
        {
            get
            {
                return this.LineTanimField;
            }
            set
            {
                this.LineTanimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OzelKod
        {
            get
            {
                return this.OzelKodField;
            }
            set
            {
                this.OzelKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Renk
        {
            get
            {
                return this.RenkField;
            }
            set
            {
                this.RenkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RenkHexKod
        {
            get
            {
                return this.RenkHexKodField;
            }
            set
            {
                this.RenkHexKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RenkKod
        {
            get
            {
                return this.RenkKodField;
            }
            set
            {
                this.RenkKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrunId
        {
            get
            {
                return this.UrunIdField;
            }
            set
            {
                this.UrunIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunKlasman
        {
            get
            {
                return this.UrunKlasmanField;
            }
            set
            {
                this.UrunKlasmanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool YerliMaliMi
        {
            get
            {
                return this.YerliMaliMiField;
            }
            set
            {
                this.YerliMaliMiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockDetail", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class StockDetail : object
    {
        
        private System.Nullable<int> DepoStokField;
        
        private System.Nullable<int> OptionStokField;
        
        private System.Nullable<int> ReyonStokField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DepoStok
        {
            get
            {
                return this.DepoStokField;
            }
            set
            {
                this.DepoStokField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OptionStok
        {
            get
            {
                return this.OptionStokField;
            }
            set
            {
                this.OptionStokField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReyonStok
        {
            get
            {
                return this.ReyonStokField;
            }
            set
            {
                this.ReyonStokField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferDetail", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class TransferDetail : object
    {
        
        private ServiceReference1.TransferEntity[] TransferListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TransferEntity[] TransferList
        {
            get
            {
                return this.TransferListField;
            }
            set
            {
                this.TransferListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSearchViewModel", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class ProductSearchViewModel : object
    {
        
        private ServiceReference1.ProductDetail ProductDetailField;
        
        private ServiceReference1.StockDetail StockDetailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProductDetail ProductDetail
        {
            get
            {
                return this.ProductDetailField;
            }
            set
            {
                this.ProductDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.StockDetail StockDetail
        {
            get
            {
                return this.StockDetailField;
            }
            set
            {
                this.StockDetailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthModel", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class AuthModel : object
    {
        
        private string AccessTokenField;
        
        private int DepoRefField;
        
        private string LanguageIsoCodeField;
        
        private string[] LokasyonListField;
        
        private int PersonelRefField;
        
        private int RoleRefField;
        
        private string UserNameField;
        
        private string ValidToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepoRef
        {
            get
            {
                return this.DepoRefField;
            }
            set
            {
                this.DepoRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageIsoCode
        {
            get
            {
                return this.LanguageIsoCodeField;
            }
            set
            {
                this.LanguageIsoCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LokasyonList
        {
            get
            {
                return this.LokasyonListField;
            }
            set
            {
                this.LokasyonListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonelRef
        {
            get
            {
                return this.PersonelRefField;
            }
            set
            {
                this.PersonelRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleRef
        {
            get
            {
                return this.RoleRefField;
            }
            set
            {
                this.RoleRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class Location : object
    {
        
        private string EtiketBarkodField;
        
        private string LokasyonAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EtiketBarkod
        {
            get
            {
                return this.EtiketBarkodField;
            }
            set
            {
                this.EtiketBarkodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LokasyonAdi
        {
            get
            {
                return this.LokasyonAdiField;
            }
            set
            {
                this.LokasyonAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LightUrunModel", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models")]
    public partial class LightUrunModel : object
    {
        
        private string BedenField;
        
        private string BoyField;
        
        private string ColorHexField;
        
        private string MerchAltGrupField;
        
        private string MerchGrupField;
        
        private string OzelKodField;
        
        private string ProductNameField;
        
        private string RenkKodField;
        
        private string RenkTanimField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beden
        {
            get
            {
                return this.BedenField;
            }
            set
            {
                this.BedenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boy
        {
            get
            {
                return this.BoyField;
            }
            set
            {
                this.BoyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorHex
        {
            get
            {
                return this.ColorHexField;
            }
            set
            {
                this.ColorHexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchAltGrup
        {
            get
            {
                return this.MerchAltGrupField;
            }
            set
            {
                this.MerchAltGrupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchGrup
        {
            get
            {
                return this.MerchGrupField;
            }
            set
            {
                this.MerchGrupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OzelKod
        {
            get
            {
                return this.OzelKodField;
            }
            set
            {
                this.OzelKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RenkKod
        {
            get
            {
                return this.RenkKodField;
            }
            set
            {
                this.RenkKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RenkTanim
        {
            get
            {
                return this.RenkTanimField;
            }
            set
            {
                this.RenkTanimField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferEntity", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class TransferEntity : object
    {
        
        private string BarkodField;
        
        private string BedenField;
        
        private string BoyField;
        
        private string ToDepoField;
        
        private System.Nullable<int> TransferMiktarField;
        
        private string TransferTipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barkod
        {
            get
            {
                return this.BarkodField;
            }
            set
            {
                this.BarkodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beden
        {
            get
            {
                return this.BedenField;
            }
            set
            {
                this.BedenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boy
        {
            get
            {
                return this.BoyField;
            }
            set
            {
                this.BoyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDepo
        {
            get
            {
                return this.ToDepoField;
            }
            set
            {
                this.ToDepoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransferMiktar
        {
            get
            {
                return this.TransferMiktarField;
            }
            set
            {
                this.TransferMiktarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferTip
        {
            get
            {
                return this.TransferTipField;
            }
            set
            {
                this.TransferTipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthCodeToTokenRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class AuthCodeToTokenRequest : object
    {
        
        private string AppStoreDeviceIdField;
        
        private string AuthCodeField;
        
        private string DeviceTypeField;
        
        private string FirebaseTokenField;
        
        private string PlatformField;
        
        private string UUIDField;
        
        private int VersionCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppStoreDeviceId
        {
            get
            {
                return this.AppStoreDeviceIdField;
            }
            set
            {
                this.AppStoreDeviceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode
        {
            get
            {
                return this.AuthCodeField;
            }
            set
            {
                this.AuthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirebaseToken
        {
            get
            {
                return this.FirebaseTokenField;
            }
            set
            {
                this.FirebaseTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Platform
        {
            get
            {
                return this.PlatformField;
            }
            set
            {
                this.PlatformField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID
        {
            get
            {
                return this.UUIDField;
            }
            set
            {
                this.UUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VersionCode
        {
            get
            {
                return this.VersionCodeField;
            }
            set
            {
                this.VersionCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLanguageIsoCodeRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class GetLanguageIsoCodeRequest : object
    {
        
        private string StoreCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreCode
        {
            get
            {
                return this.StoreCodeField;
            }
            set
            {
                this.StoreCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLanguageIsoCodeResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class GetLanguageIsoCodeResponse : object
    {
        
        private int DepoRefField;
        
        private string LanguageIsoCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepoRef
        {
            get
            {
                return this.DepoRefField;
            }
            set
            {
                this.DepoRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageIsoCode
        {
            get
            {
                return this.LanguageIsoCodeField;
            }
            set
            {
                this.LanguageIsoCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferExceptionLogRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class TransferExceptionLogRequest : object
    {
        
        private ServiceReference1.ExceptionLogModel[] ExceptionLogModelListField;
        
        private string UUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExceptionLogModel[] ExceptionLogModelList
        {
            get
            {
                return this.ExceptionLogModelListField;
            }
            set
            {
                this.ExceptionLogModelListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID
        {
            get
            {
                return this.UUIDField;
            }
            set
            {
                this.UUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionLogModel", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Domain")]
    public partial class ExceptionLogModel : object
    {
        
        private string ExceptionDateField;
        
        private string MessageField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionDate
        {
            get
            {
                return this.ExceptionDateField;
            }
            set
            {
                this.ExceptionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MobileGetDataMatrixInfoRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class MobileGetDataMatrixInfoRequest : object
    {
        
        private string BarcodeField;
        
        private int QuantityField;
        
        private string StoreCodeField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode
        {
            get
            {
                return this.BarcodeField;
            }
            set
            {
                this.BarcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreCode
        {
            get
            {
                return this.StoreCodeField;
            }
            set
            {
                this.StoreCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MobileGetDataMatrixInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class MobileGetDataMatrixInfoResponse : object
    {
        
        private bool HasErrorField;
        
        private ServiceReference1.MobileGetDataMatrixInfoEntity[] MobileGetDataMatrixInfoEntityListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError
        {
            get
            {
                return this.HasErrorField;
            }
            set
            {
                this.HasErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.MobileGetDataMatrixInfoEntity[] MobileGetDataMatrixInfoEntityList
        {
            get
            {
                return this.MobileGetDataMatrixInfoEntityListField;
            }
            set
            {
                this.MobileGetDataMatrixInfoEntityListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MobileGetDataMatrixInfoEntity", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class MobileGetDataMatrixInfoEntity : object
    {
        
        private int CountyRefField;
        
        private int DataMatrixIdField;
        
        private string ZPLCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountyRef
        {
            get
            {
                return this.CountyRefField;
            }
            set
            {
                this.CountyRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataMatrixId
        {
            get
            {
                return this.DataMatrixIdField;
            }
            set
            {
                this.DataMatrixIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZPLCode
        {
            get
            {
                return this.ZPLCodeField;
            }
            set
            {
                this.ZPLCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MobileRollBackDataMatrixInfoRequest", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Request")]
    public partial class MobileRollBackDataMatrixInfoRequest : object
    {
        
        private int DataMatrixIDField;
        
        private string StoreCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataMatrixID
        {
            get
            {
                return this.DataMatrixIDField;
            }
            set
            {
                this.DataMatrixIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreCode
        {
            get
            {
                return this.StoreCodeField;
            }
            set
            {
                this.StoreCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MobileRollBackDataMatrixInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/Mobile.WCF.Models.Response")]
    public partial class MobileRollBackDataMatrixInfoResponse : object
    {
        
        private bool HasErrorField;
        
        private bool IsRollBackField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError
        {
            get
            {
                return this.HasErrorField;
            }
            set
            {
                this.HasErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRollBack
        {
            get
            {
                return this.IsRollBackField;
            }
            set
            {
                this.IsRollBackField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IJsonRestDataService")]
    public interface IJsonRestDataService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/GetLabelInfo", ReplyAction="http://tempuri.org/IJsonRestDataService/GetLabelInfoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetLabelInfoResponse> GetLabelInfoAsync(ServiceReference1.GetLabelInfoRequest getLabelInfoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/Authenticate", ReplyAction="http://tempuri.org/IJsonRestDataService/AuthenticateResponse")]
        System.Threading.Tasks.Task<ServiceReference1.AuthenticateResponse> AuthenticateAsync(ServiceReference1.AuthenticateRequest authenticateRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/SearchProduct", ReplyAction="http://tempuri.org/IJsonRestDataService/SearchProductResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ProductSearchResponse> SearchProductAsync(ServiceReference1.ProductSearchRequest searchProductRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/AuthCodeToToken", ReplyAction="http://tempuri.org/IJsonRestDataService/AuthCodeToTokenResponse")]
        System.Threading.Tasks.Task<ServiceReference1.AuthCodeToTokenResponse> AuthCodeToTokenAsync(ServiceReference1.AuthCodeToTokenRequest authCodeToTokenRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/GetLanguageIsoCode", ReplyAction="http://tempuri.org/IJsonRestDataService/GetLanguageIsoCodeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetLanguageIsoCodeResponse> GetLanguageIsoCodeAsync(ServiceReference1.GetLanguageIsoCodeRequest getLanguageIsoCodeRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/TransferExceptionLog", ReplyAction="http://tempuri.org/IJsonRestDataService/TransferExceptionLogResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TransferExceptionLogResponse> TransferExceptionLogAsync(ServiceReference1.TransferExceptionLogRequest transferExceptionLogRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/GetLocation", ReplyAction="http://tempuri.org/IJsonRestDataService/GetLocationResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetLocationResponse> GetLocationAsync(ServiceReference1.GetLocationRequest getLocationRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/SubmitLocationAction", ReplyAction="http://tempuri.org/IJsonRestDataService/SubmitLocationActionResponse")]
        System.Threading.Tasks.Task<ServiceReference1.SubmitLocationActionResponse> SubmitLocationActionAsync(ServiceReference1.SubmitLocationActionRequest submitLocationActionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/GetLocations", ReplyAction="http://tempuri.org/IJsonRestDataService/GetLocationsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetLocationsResponse> GetLocationsAsync(ServiceReference1.GetLocationsRequest getLocationsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/GetLightUrunModel", ReplyAction="http://tempuri.org/IJsonRestDataService/GetLightUrunModelResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetLightUrunModelResponse> GetLightUrunModelAsync(ServiceReference1.GetLightUrunModelRequest getLightUrunModelRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/MobileGetDataMatrixInfo", ReplyAction="http://tempuri.org/IJsonRestDataService/MobileGetDataMatrixInfoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.MobileGetDataMatrixInfoResponse> MobileGetDataMatrixInfoAsync(ServiceReference1.MobileGetDataMatrixInfoRequest mobileGetDataMatrixInfoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/MobileRollBackDataMatrixInfo", ReplyAction="http://tempuri.org/IJsonRestDataService/MobileRollBackDataMatrixInfoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.MobileRollBackDataMatrixInfoResponse> MobileRollBackDataMatrixInfoAsync(ServiceReference1.MobileRollBackDataMatrixInfoRequest mobileRollBackDataMatrixInfoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/SendNotificationForMutsDemand", ReplyAction="http://tempuri.org/IJsonRestDataService/SendNotificationForMutsDemandResponse")]
        System.Threading.Tasks.Task<ServiceReference1.SendNotificationForMutsDemandResponse> SendNotificationForMutsDemandAsync(ServiceReference1.SendNotificationForMutsDemandRequest sendNotificationForMutsDemandRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/CheckHesCode", ReplyAction="http://tempuri.org/IJsonRestDataService/CheckHesCodeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CheckHesCodeResponse> CheckHesCodeAsync(ServiceReference1.CheckHesCodeRequest checkHesCodeRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJsonRestDataService/Test", ReplyAction="http://tempuri.org/IJsonRestDataService/TestResponse")]
        System.Threading.Tasks.Task TestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IJsonRestDataServiceChannel : ServiceReference1.IJsonRestDataService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class JsonRestDataServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IJsonRestDataService>, ServiceReference1.IJsonRestDataService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public JsonRestDataServiceClient() : 
                base(JsonRestDataServiceClient.GetDefaultBinding(), JsonRestDataServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.JsonRestDataServiceBinding_IJsonRestDataService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JsonRestDataServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(JsonRestDataServiceClient.GetBindingForEndpoint(endpointConfiguration), JsonRestDataServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JsonRestDataServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(JsonRestDataServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JsonRestDataServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(JsonRestDataServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JsonRestDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLabelInfoResponse> GetLabelInfoAsync(ServiceReference1.GetLabelInfoRequest getLabelInfoRequest)
        {
            return base.Channel.GetLabelInfoAsync(getLabelInfoRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AuthenticateResponse> AuthenticateAsync(ServiceReference1.AuthenticateRequest authenticateRequest)
        {
            return base.Channel.AuthenticateAsync(authenticateRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ProductSearchResponse> SearchProductAsync(ServiceReference1.ProductSearchRequest searchProductRequest)
        {
            return base.Channel.SearchProductAsync(searchProductRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AuthCodeToTokenResponse> AuthCodeToTokenAsync(ServiceReference1.AuthCodeToTokenRequest authCodeToTokenRequest)
        {
            return base.Channel.AuthCodeToTokenAsync(authCodeToTokenRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLanguageIsoCodeResponse> GetLanguageIsoCodeAsync(ServiceReference1.GetLanguageIsoCodeRequest getLanguageIsoCodeRequest)
        {
            return base.Channel.GetLanguageIsoCodeAsync(getLanguageIsoCodeRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TransferExceptionLogResponse> TransferExceptionLogAsync(ServiceReference1.TransferExceptionLogRequest transferExceptionLogRequest)
        {
            return base.Channel.TransferExceptionLogAsync(transferExceptionLogRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLocationResponse> GetLocationAsync(ServiceReference1.GetLocationRequest getLocationRequest)
        {
            return base.Channel.GetLocationAsync(getLocationRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SubmitLocationActionResponse> SubmitLocationActionAsync(ServiceReference1.SubmitLocationActionRequest submitLocationActionRequest)
        {
            return base.Channel.SubmitLocationActionAsync(submitLocationActionRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLocationsResponse> GetLocationsAsync(ServiceReference1.GetLocationsRequest getLocationsRequest)
        {
            return base.Channel.GetLocationsAsync(getLocationsRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLightUrunModelResponse> GetLightUrunModelAsync(ServiceReference1.GetLightUrunModelRequest getLightUrunModelRequest)
        {
            return base.Channel.GetLightUrunModelAsync(getLightUrunModelRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MobileGetDataMatrixInfoResponse> MobileGetDataMatrixInfoAsync(ServiceReference1.MobileGetDataMatrixInfoRequest mobileGetDataMatrixInfoRequest)
        {
            return base.Channel.MobileGetDataMatrixInfoAsync(mobileGetDataMatrixInfoRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MobileRollBackDataMatrixInfoResponse> MobileRollBackDataMatrixInfoAsync(ServiceReference1.MobileRollBackDataMatrixInfoRequest mobileRollBackDataMatrixInfoRequest)
        {
            return base.Channel.MobileRollBackDataMatrixInfoAsync(mobileRollBackDataMatrixInfoRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SendNotificationForMutsDemandResponse> SendNotificationForMutsDemandAsync(ServiceReference1.SendNotificationForMutsDemandRequest sendNotificationForMutsDemandRequest)
        {
            return base.Channel.SendNotificationForMutsDemandAsync(sendNotificationForMutsDemandRequest);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CheckHesCodeResponse> CheckHesCodeAsync(ServiceReference1.CheckHesCodeRequest checkHesCodeRequest)
        {
            return base.Channel.CheckHesCodeAsync(checkHesCodeRequest);
        }
        
        public System.Threading.Tasks.Task TestAsync()
        {
            return base.Channel.TestAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.JsonRestDataServiceBinding_IJsonRestDataService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.JsonRestDataServiceBinding_IJsonRestDataService))
            {
                return new System.ServiceModel.EndpointAddress("http://nagras-local.lcwaikiki.com/TemaMobileServices/JsonRestDataService.svc/wcf");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return JsonRestDataServiceClient.GetBindingForEndpoint(EndpointConfiguration.JsonRestDataServiceBinding_IJsonRestDataService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return JsonRestDataServiceClient.GetEndpointAddress(EndpointConfiguration.JsonRestDataServiceBinding_IJsonRestDataService);
        }
        
        public enum EndpointConfiguration
        {
            
            JsonRestDataServiceBinding_IJsonRestDataService,
        }
    }
}
